
name: DAppV2 CI

on: [push, pull_request]

env:
  REACT_APP_CHAIN_ID: 97
  REACT_APP_RPC: 'https://data-seed-prebsc-2-s1.binance.org:8545/'
  REACT_APP_RPC_ETH: 'https://data-seed-prebsc-1-s1.binance.org:8545/'
  REACT_APP_NET: 'testnet'
  REACT_APP_ADDR: '0x43364696e478E344E95831CE8427623202e5CBFb'
  REACT_APP_CONTRACT_ADDR: '0xd46e8dd67c5d32be8058bb8eb970870f07244567'

jobs:
  sanity-checks:
    name: Sanity Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build the app 
        run: npm ci --ignore-scripts
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm test -- --watchAll=false --ci --coverage
