
name: DAppV2 CI

on: [push, pull_request]

jobs:
  sanity-checks:
    name: Sanity Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm test -- --watchAll=false --ci --coverage